# Generated by Django 3.2.5 on 2021-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='essay',
            field=models.TextField(max_length=3000),
        ),
    ]
