# Generated by Django 3.2.5 on 2021-07-20 13:39

from django.db import migrations
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_essay_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),

        ),
    ]
