# Generated by Django 3.2.5 on 2021-07-20 14:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_essay_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
